version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/standup-raven/standup-raven/server
  govet:
    enable-all: true
  misspell:
    locale: US
  gocritic:
    disabled-checks:
      - ifElseChain

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unused
    - whitespace
  formatters:
    enable:
      - gofmt
      - goimports

issues:
  exclude:
    - 'declaration of "(err|ctx)" shadows declaration at'
  exclude-rules:
    - path: server/standup/main.go
      linters:
        - govet
    - path: _test\.go
      linters:
        - bodyclose
