version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    govet:
      enable-all: true
    misspell:
      locale: US
    gocritic:
      disabled-checks:
        - ifElseChain
  exclusions:
    rules:
      - path: server/standup/main.go
        linters:
          - govet
      - path: _test\.go
        linters:
          - bodyclose
    presets:
      - comments
      - std-error-handling
      - common-false-positives

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/standup-raven/standup-raven/server
